### ISSUE TITLE
ESLint rules from plugins should be optional

### ISSUE THREAD

**Issue by akxcv** [umbrellio/code-style#19]
Right now, all rules are enabled, regardless of whether the user uses React, JSX, Flow and so on. I suggest we do something similar to [kentcdodds/eslint-config-kentcdodds](https://github.com/kentcdodds/eslint-config-kentcdodds).

**Comment by JelF** [comment]
Good idea, would it be problems with yaml?

**Comment by akxcv** [comment]
There shouldn't be any problems AFAIK.

**Comment by akxcv** [comment]
Closed via #21.
