### ISSUE TITLE
[Rubocop] Security/YAMLLoad

### ISSUE THREAD

**Issue by JelF** [umbrellio/code-style#26]
It seems it should be disabled in most cases

**Comment by JelF** [comment]
According to https://ruby-doc.org/stdlib-2.1.0/libdoc/psych/rdoc/Psych.html#safe_load-method, we can configure yaml to do this. however, user input should never be loaded via yaml, so it does not make much sence

**Comment by tycooon** [comment]
+1 let’s disable.
