### ISSUE TITLE
What is better naming, eslint or javascript?

### ISSUE THREAD

**Issue by JelF** [umbrellio/code-style#3]
If the subject is code style, it should be named 'javascript' (or 'es6') and if the subject is eslint config, it should be named 'eslint'. It may be a tough choise about naming, but as far as i see, there is no eslint strict dependency so if we want to add config for different linter, it would not be hard to combine it in one npm package, which could be used in both.

Pros of 'eslint' naming:
- We can separate eslint configuration from e.g. JSHint

Pros of 'javascript' / 'es6' naming:
- We can add our code style guide (like ruby style guide in https://github.com/bbatsov/ruby-style-guide)
- I wish to develop 'ruby' style guides with markdown documentation, which would describe all deviatoins from bbatsov/ruby-style-guide we are forcing / allowing and refer it's content in rubocop configuration file, it would be a consistent naming in this case

**Comment by JelF** [comment]
@akxcv what do you think about this?

**Comment by akxcv** [comment]
I had some thoughts about the naming, too, and here are my conclusions (for now, at least):

- No matter what, the *package* should be called "eslint" since that's what it targets.
- If we will ever need to target another linter, we'll just add a *separate* package for that linter.
- If we want to document our code style in Markdown (which would be great), we can have the following file structure:

```
javascript/
|- eslint/
|- jshint/
|- README.md
ruby/
|- rubocop/
|- README.md
```

**Comment by JelF** [comment]
> If we want to document our code style in Markdown (which would be great), we can have the following file structure

It sounds cool and logical, i like this. I think, this structure could be applied immediately

**Comment by akxcv** [comment]
Let's not change the structure until we actually need to.

**Comment by JelF** [comment]
I guess we need to do it with separate commit and i'll start developing rubocop configuration and ruby docs at monday

**Comment by JelF** [comment]
nevermind, i understood that i have issues with verifly and should spend some time there

**Comment by akxcv** [comment]
Closing this for now.
