### ISSUE TITLE
[Rubocop] Metrics/BlockLength should be disabled

### ISSUE THREAD

**Issue by JelF** [umbrellio/code-style#35]
or possibly configured, but this configuration would take huge amount of time :(

**Comment by TrumpClone** [comment]
approved

**Comment by akxcv** [comment]
Wouldn't it make sense to disable this rule only for certain types of files (configuration, specs, migrations, etc)? I think it's pretty useful for the regular code.

**Comment by JelF** [comment]
@akxcv This forces to replace
```
Foo = Struct.new(:foo) do
```
with
```
Foo = Struct.new(:foo)
class Foo 
```

After some thinking, i realised that second variant is someway better, because class defenition always better than class_exec. Anyway, it requies some guidelines to leave it enabled in app/ and lib/

**Comment by JelF** [comment]
In most cases, max block length is restricted by module length or method length, so it seems to be useless in regular code

**Comment by akxcv** [comment]
Yeah, that makes sense. If it's restricted by module/method (class?) length anyway, I'm for disabling block length completely.

**Comment by akxcv** [comment]
What's the status of this? What are we waiting for?

**Comment by JelF** [comment]
Right now i don't sure, that long class_exec and module_exec blocks are good in general. If they are not, this cop would disallow them. And the reason i wanted to disable this cop is exactly that it disallowed them

**Comment by JelF** [comment]
The problem is, e.g., we have `Struct.new() do` and whole class defenition is not recognized as a class defenition by static analizers

**Comment by akxcv** [comment]
Well, I think we should generally avoid metaprogramming outside library code. But, if that's the primary reason for disabling the cop, we shouldn't IMO.
We could disable it for configs, specs, and migrations and leave it in for business logic.

**Comment by JelF** [comment]
Seems reasonable. We can discuss it at monday
