### ISSUE TITLE
[ESLint] Up to v4.0.0

### ISSUE THREAD

**Issue by TrumpClone** [umbrellio/code-style#36]
WDYT?

**Comment by JelF** [comment]
I looked for changelog (https://github.com/eslint/eslint/blob/master/CHANGELOG.md), it should not produce much problems

**Comment by JelF** [comment]
AFAIU, the major change was upgrade to es6, so if it not break plugins, there is nothing special

**Comment by akxcv** [comment]
As far as I can tell, the only useful rules are [switch-colon-spacing](http://eslint.org/docs/rules/switch-colon-spacing) and [no-buffer-constructor](http://eslint.org/docs/rules/no-buffer-constructor). I don't think there's a point in updating _right now_, so we can definitely wait for v4.1.0.

**Comment by akxcv** [comment]
Closed by #47.
