### ISSUE TITLE
[General] Setup github contribution system

### ISSUE THREAD

**Issue by JelF** [umbrellio/code-style#46]
- [ ] Setup CONTRIBUTING.md
  https://help.github.com/articles/setting-guidelines-for-repository-contributors/
  Add general suggestions there:
  - name PR and commits like `[Rubocop] force double quotes`
  - name branches like `rubocop/force-double-quotes`
  - never `merge` into master, choise from `rebase on master` and `squash and merge`

- [ ] Setup `rubocop`, `eslint`, and `stylelint` labels for issues and PR
- [ ] Setup PR and Issue templates

**Comment by JelF** [comment]
@akxcv, i need some review in naming rules. I suggest: 

- Lables
  - `rubocop`, `eslint`, `stylelint`, `documentation`
  - `bug`, `duplicate`, `invalid`, `question`, `wontfix`

- For PR / commit
  - `[Rubocop] force double quotes`
  - `[Eslint, Rubocop] force double quotes` - alphabetical order
  - `[General] use double quotes in documentation`

- And for branches
  - `rubocop/force-double-quotes`
  - `eslint+rubocop/force-double-quotes`
  - `general/use-double-quotes-in-documentation`

**Comment by akxcv** [comment]
Setting up a contribution guide is a great idea!

A few thoughts:

- Do we need linter-specific labels for PRs and issues? In my opinion, prefixes in PRs and issues should be enough (and I do suggest applying this convention to issues, too).
- **Squash and merge** and **Rebase and merge**: the guidelines for selecting an option should be clear. My suggestions (we should also provide some examples):
  - Use **Rebase and merge** when *each commit of the PR contains a clear, distinct change and is named accordingly, following our naming guidelines*.
  - Use **Rebase and merge** when *the PR only has one well-named commit*. 
  - Use **Squash and merge** when *the whole pull request should really consist of only one commit but has multiple*.
- Linter names should have clear capitalization: **Rubocop**, **ESLint**, **Stylelint**.

EDIT: Another option for "PR merging guidelines" is to simply forbid merging for everyone except some people to merge the PRs :)

**Comment by JelF** [comment]
> Do we need linter-specific labels for PRs and issues? In my opinion, prefixes in PRs and issues should be enough (and I do suggest applying this convention to issues, too).

labels are used for fast-filtering, we will need them some day later. IMO

> EDIT: Another option for "PR merging guidelines" is to simply forbid merging for everyone except some people to merge the PRs :)

Don't like this

**Comment by JelF** [comment]
> EDIT: Another option for "PR merging guidelines" is to simply forbid merging for everyone except some people to merge the PRs :)
I think, we should suggest over forbid, because
1) We still have to review and check code before publish it, so it would break nothing
2) Contributing gædlines should help contributers to interact with themself, not to make it a `star` topology with us in middle

**Comment by JelF** [comment]
And 3) we can go on a vacation and it should not stop work

**Comment by tycooon** [comment]
🤔
